// src/components/ColorPicker/ColorPicker.tsx
import React from 'react';
import { Popover, Tooltip } from '@mantine/core';
import { Check } from 'lucide-react';
import clsx from 'clsx';
import { useAppStore } from '@/store/useAppStore';
import { getT } from '@/utils';
import styles from './ColorPicker.module.css';

const PALETTE = [
  '#26A69A',
  '#66BB6A',
  '#9CCC65',
  '#D4E157',
  '#FFCA28',
  '#FFA726',
  '#FF7043',
  '#8D6E63',
  '#BDBDBD',
  '#78909C',
  '#29B6F6',
  '#5C6BC0',
  '#7E57C2',
  '#EC407A',
  '#ef5350',
  '#607D8B',
  '#4CAF50',
  '#ff5252',
];

interface ColorPickerProps {
  isNepali?: boolean;
}

export const ColorPicker: React.FC<ColorPickerProps> = ({ isNepali = true }) => {
  const { config, setBackgroundColor } = useAppStore();
  const [opened, setOpened] = React.useState(false);
  const t = getT(isNepali);

  return (
    <div className={styles.wrapper}>
      <Popover
        opened={opened}
        onChange={setOpened}
        position="top"
        withArrow
        shadow="md"
        radius="md"
        offset={12}
      >
        <Popover.Target>
          <Tooltip label={t.colorPickerTooltip} withArrow position="top">
            <button
              className={styles.triggerBtn}
              onClick={() => setOpened((o) => !o)}
              style={{ backgroundColor: config.backgroundColor }}
              aria-label={t.colorPickerTooltip}
            />
          </Tooltip>
        </Popover.Target>

        <Popover.Dropdown style={{ padding: '8px' }}>
          <div className={styles.paletteGrid}>
            {PALETTE.map((color) => {
              const isSelected = color === config.backgroundColor;
              return (
                <button
                  key={color}
                  className={clsx(styles.colorSwatch, isSelected && styles.selectedSwatch)}
                  style={{ backgroundColor: color }}
                  onClick={() => {
                    setBackgroundColor(color);
                    setOpened(false);
                  }}
                  aria-label={`Select color ${color}`}
                >
                  {isSelected && <Check size={14} color="#ffffff" strokeWidth={3} />}
                </button>
              );
            })}
          </div>
        </Popover.Dropdown>
      </Popover>
    </div>
  );
};

// src/components/ColorPicker.vue
<template>
  <div class="colorPicker" ref="colorPicker">
    <div class="handle" @click="toggleActiveStatus()"></div>
    <div class="palette" v-if="active">
      <div
        class="colorItem"
        :class="{'--selected': color === backgroundColor}"
        v-for="(color, index) in colors"
        :key="index"
        :style="'background-color: ' + color"
        @click="selectColor(color)"
      ></div>
    </div>
  </div>
</template>

<script>
import { mapFields } from "vuex-map-fields";

export default {
  name: "Toolbar",
  data() {
    return {
      active: false,
      colors: [
        "#26A69A",
        "#66BB6A",
        "#9CCC65",
        "#D4E157",
        "#FFCA28",
        "#FFA726",
        "#FF7043",
        "#8D6E63",
        "#BDBDBD",
        "#78909C",
        "#29B6F6",
        "#5C6BC0",
        "#7E57C2",
        "#EC407A",
        "#ef5350",
        "#607D8B",
        "#4CAF50",
        "#ff5252",
      ],
    };
  },

  methods: {
    toggleActiveStatus() {
      this.active = !this.active;
    },

    selectColor(color) {
      this.backgroundColor = color;
      this.toggleActiveStatus();
    },
  },

  computed: {
    ...mapFields({
      nightMode: "config.nightMode",
      fullScreen: "config.fullScreen",
      backgroundColor: "config.backgroundColor",
    }),
  },
};
</script>

<style scoped lang="scss">
.colorPicker {
  position: relative;
  $size: 18px;
  .handle {
    height: $size;
    width: $size;
    border-radius: 50%;
    border: 1px solid $white;
    background: transparent;
    cursor: pointer;
  }

  .palette {
    position: absolute;
    min-width: 200px;
    border-radius: 5px;
    background-color: $white;
    transform: translate(
      calc(-100% + #{$size}),
      calc(-100% - #{$size} - 8px)
    );
    padding: 0.25rem;
    display: flex;
    flex-wrap: wrap;
    justify-content: center;
    @include shadow;

    .colorItem {
      height: $size + 5;
      width: $size + 5;
      border-radius: 50%;
      cursor: pointer;
      margin: 0.25rem;
      border: 1px solid $white;

      &.--selected{
        border-color: $dark-1;
      }
    }
  }
}
</style>
